import streamlit as st

DEXSCREENER_URL = "https://api.dexscreener.com/latest/dex/search?q=SOL"

MIN_LIQUIDITY = 1000
MIN_VOLUME_24H = 1000

MIN_LIQUIDITY_SIGNAL = 20000
VOLUME_SPIKE_THRESHOLD = 0.5 

INTERVAL = 300  
DB_NAME = "memecoins.db"

TELEGRAM_BOT_TOKEN = st.secrets["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHAT_ID = st.secrets["TELEGRAM_CHAT_ID"]

AI_PREDICT_PERIODS = 6 
AI_PREDICT_FREQ = '5min'
