import os

DEXSCREENER_URL = "https://api.dexscreener.com/latest/dex/search?q=SOL"

MIN_LIQUIDITY = 20000     
MIN_VOLUME_24H = 10000       
MAX_VOLUME_LIQUIDITY_RATIO = 5 
MAX_PRICE_SPIKE = 1.5           
MIN_PAIR_AGE_SECONDS = 300 

INTERVAL = 300  

DB_NAME = "memecoins.db"

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

INITIAL_BALANCE = 1000
RISK_PER_TRADE = 0.01
SLIPPAGE = 0.01
FEE = 0.003